### ISSUE TITLE
on_raw_004 "not enough values to unpack"

### ISSUE THREAD

**Issue by bukowa** [Shizmob/pydle#147]
````python
ERROR:MyOwnBot:chat.example:Failed to execute on_raw_004 handler.
Traceback (most recent call last):
  File "...pydle\client.py", line 422, in on_raw
    await handler(message)
  File "...\pydle\features\rfc1459\client.py", line 762, in on_raw_004
    target, hostname, ircd, user_modes, channel_modes = message.params[:5]
ValueError: not enough values to unpack (expected 5, got 2)
````

**Comment by theunkn0wn1** [comment]
@bukowa Can you give me some context on how you reached this state?

**Comment by bukowa** [comment]
@theunkn0wn1 its just because 
````python
len(message.params) < 5
````
in my case this happens in welcome message, just before `on_connect`

**Comment by theunkn0wn1** [comment]
insufficient information to reproduce, closing as stale.
