### ISSUE TITLE
errors when user quits

### ISSUE THREAD

**Issue by flv0** [Shizmob/pydle#29]
I keep getting this kind of error when a user quits (on master): 
```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xb6c87e84>, <pydle.features.rfc1459.parsing.RFC1459Message object at 0xb6cad56c>)
Traceback (most recent call last):
  File "/home/flavi0/.local/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/home/flavi0/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/flavi0/.local/lib/python3.4/site-packages/pydle-0.8.0-py3.4.egg/pydle/features/rfc1459/client.py", line 719, in on_raw_quit
    self._destroy_user(nick)
TypeError: _destroy_user() missing 1 required positional argument: 'channel'
```

**Comment by Shizmob** [comment]
Should be fixed now, thanks for reporting!

**Comment by flv0** [comment]
Don't know if it's directly related, but now I get this, so reopening:
```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xb6c39e84>, <pydle.features.rfc1459.parsing.RFC1459Message object at 0xb6c514ec>)
Traceback (most recent call last):
  File "/home/flavi0/.local/lib/python3.4/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/home/flavi0/.local/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/flavi0/.local/lib/python3.4/site-packages/pydle-0.8.0-py3.4.egg/pydle/features/rfc1459/client.py", line 719, in on_raw_quit
    self._destroy_user(nick)
  File "/home/flavi0/.local/lib/python3.4/site-packages/pydle-0.8.0-py3.4.egg/pydle/features/rfc1459/client.py", line 106, in _destroy_user
    if status in ch['modes'] and nickname in ch['modes'][status]:
NameError: name 'nickname' is not defined
```

**Comment by Shizmob** [comment]
Seems like some code didn’t survive refactoring properly, apologies!
That issue should be fixed now as well.
