### ISSUE TITLE
Attempting to 'pip install pydle' fails if tornado isn't already installed

### ISSUE THREAD

**Issue by ayust** [Shizmob/pydle#30]
This is due to setup.py importing `pydle`, which tries to import tornado before pip can actually set anything up.

```
$ pip install pydle
Downloading/unpacking pydle
  Downloading pydle-0.8.0.tar.gz
  Running setup.py (path:/home/...../venv/build/pydle/setup.py) egg_info for package pydle
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/...../venv/build/pydle/setup.py", line 2, in <module>
        import pydle
      File "/home/...../venv/build/pydle/pydle/__init__.py", line 1, in <module>
        from . import async, connection, protocol, client, features
      File "/home/...../venv/build/pydle/pydle/async.py", line 10, in <module>
        import tornado.concurrent
    ImportError: No module named 'tornado'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/...../venv/build/pydle/setup.py", line 2, in <module>

    import pydle

  File "/home/...../venv/build/pydle/pydle/__init__.py", line 1, in <module>

    from . import async, connection, protocol, client, features

  File "/home/...../venv/build/pydle/pydle/async.py", line 10, in <module>

    import tornado.concurrent

ImportError: No module named 'tornado'

----------------------------------------
Cleaning up...
```

It looks like you solved this in 902d6e6b03158548a8e77a3c04bf426dfffce37c, but there hasn't been a PyPI release since then, so pip is still trying to grab a broken version.

Any chance you could push a new release?

**Comment by Shizmob** [comment]
Hi! Sorry for the delayed response.

Sure thing, I'll try to get a release out tomorrrow.

**Comment by Shizmob** [comment]
Should be arranged now! Thanks for reporting!

**Comment by Shizmob** [comment]
And, after some administrative errors, it's /properly/ fixed now.

**Comment by ayust** [comment]
Thanks! (And I can commiserate with, um, administrative error when releasing packages. >_>)
