### ISSUE TITLE
ValueError thrown when using disconnect()

### ISSUE THREAD

**Issue by Polsaker** [Shizmob/pydle#42]
> ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd97c7ed1e0>, True)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 604, in _run_callback
>     ret = callback()
>   File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/pydle/client.py", line 122, in _disconnect
>     self.connection.off('read', self.on_data)
>   File "/usr/local/lib/python3.4/dist-packages/pydle/connection.py", line 295, in off
>     self.handlers[method].remove(callback)
> ValueError: list.remove(x): x not in list

**Comment by Shizmob** [comment]
Thanks for the report! I thought I had fixed this a while back, could you please confirm this is still the case on the latest git version?

**Comment by Polsaker** [comment]
Ugh, that happened on the latest pypi version, but when testing on the latest git I get additional errors:

> ERROR:Donger:alcatraz:Unexpected disconnect. Attempting to reconnect.
> ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f35104fbd90>, True)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 604, in _run_callback
>     ret = callback()
>   File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/home/polsaker/pydle/pydle/client.py", line 119, in _disconnect
>     self.connection.off('read', self.on_data)
>   File "/home/polsaker/pydle/pydle/connection.py", line 295, in off
>     self.handlers[method].remove(callback)
> ValueError: list.remove(x): x not in list
> ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f35104fb950>, False)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 604, in _run_callback
>     ret = callback()
>   File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/home/polsaker/pydle/pydle/client.py", line 119, in _disconnect
>     self.connection.off('read', self.on_data)
>   File "/home/polsaker/pydle/pydle/connection.py", line 295, in off
>     self.handlers[method].remove(callback)
> ValueError: list.remove(x): x not in list
> DEBUG:tornado.general:Error deleting fd from IOLoop
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 736, in remove_handler
>     self._impl.unregister(fd)
> FileNotFoundError: [Errno 2] No such file or directory
>

**Comment by Shizmob** [comment]
Hmm, concerning. I've just pushed two commits that make the handling a bit more robust.
Could I ask you to see if the issue still occurs on latest git now? :)

**Comment by Polsaker** [comment]
The first error disappeared. Now I only get 
ERROR:Donger

> :alcatraz:Unexpected disconnect. Attempting to reconnect.
> ERROR:pydle.client:Unexpected disconnect. Attempting to reconnect within 5 seconds.
> DEBUG:tornado.general:Error deleting fd from IOLoop
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 736, in remove_handler
>     self._impl.unregister(fd)
> FileNotFoundError: [Errno 2] No such file or directory

and then the script exits completely

**Comment by Shizmob** [comment]
Hmm, odd. I can't directly pinpoint a reason for this to happen. Are you running multiple clients in a `ClientPool`, or just a single one?

**Comment by Polsaker** [comment]
It's a single client

**Comment by Polsaker** [comment]
Also, these messages:

> ERROR:Donger:alcatraz:Unexpected disconnect. Attempting to reconnect.
> ERROR:pydle.client:Unexpected disconnect. Attempting to reconnect within 5 seconds.
> ERROR:pydle.client:Unexpected disconnect. Attempting to reconnect within 10 seconds.

make me think that it's trying to reconnect and failing, various times.
