### ISSUE TITLE
Graceful Disconnect fails

### ISSUE THREAD

**Issue by Harmon758** [Shizmob/pydle#99]
Attempting to disconnect the client results in:
```
Task exception was never retrieved
future: <Task finished coro=<BasicClient._disconnect() done, defined at C:\Program Files\Python37\lib\site-packages\pydle\client.py:124> exception=AttributeError("'_WindowsSelectorEventLoop' object has no attribute 'schedule'")>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\pydle\client.py", line 133, in _disconnect
    self.connection.stop()
  File "C:\Program Files\Python37\lib\site-packages\pydle\connection.py", line 123, in stop
    self.eventloop.schedule(lambda: self.eventloop.stop())
AttributeError: '_WindowsSelectorEventLoop' object has no attribute 'schedule'
```
This is due to there not being a schedule method for an asyncio event loop.

**Comment by theunkn0wn1** [comment]
Fixed for v0.9.0, release pending.
